version: '3'

services:
  postgres-container:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "senha123"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\sallo\Desktop\Steeck\steeckr-backend\postgresql-docker
    networks:
      - postgres-compose-network
      
  pgadmin-container:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rfgvieira@usp.br"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - "16543:80"
    depends_on:
      - postgres-container
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

